// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahdurcskupcmijxondhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoZHVyY3NrdXBjbWlqeG9uZGhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMzYxMjgsImV4cCI6MjA2NjYxMjEyOH0.l_Bzx2hmDYAgPS-WGAs0eU-9eQNJnaZsU1nVwcYYuNU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);